import type { AssetType } from "../domain/types.js";

export type MetaOnePriority = "P0" | "P1";
export type MetaOnePhase = "compiler" | "serving";
export type MetaOneAuthority = "primary" | "supplemental" | "fallback" | "verification";

export interface MetaOneEndpointCapability {
  key: string;
  path: string;
  alternativePaths?: string[];
  priority: MetaOnePriority;
  phase: MetaOnePhase;
  authority: MetaOneAuthority;
  role: "search" | "read" | "expand";
  assetTypes: AssetType[];
  relations: string[];
  description: string;
  runtime: "design" | "runtime" | "cross-service";
}

/**
 * Contract-derived routing inventory. Paths and semantic roles come from the
 * reviewed MetaOne contracts. Request authentication and raw JSON field mapping
 * remain provider concerns and require live payload fixtures.
 */
export const METAONE_ENDPOINTS: readonly MetaOneEndpointCapability[] = [
  {
    key: "logical-model-list",
    path: "/entity/v1/entityList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["LOGICAL_ENTITY"],
    relations: [],
    description: "Discover canonical logical entities.",
    runtime: "design",
  },
  {
    key: "logical-attributes",
    path: "/entity/v1/attributeByEntityId",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["LOGICAL_ENTITY", "LOGICAL_ATTRIBUTE", "PHYSICAL_COLUMN"],
    relations: ["HAS_ATTRIBUTE", "MAPS_TO"],
    description: "Expand a logical entity to declared attributes and explicit mappings.",
    runtime: "design",
  },
  {
    key: "logical-entity-relations",
    path: "/entity/v1/entityBuziRelation",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["LOGICAL_ENTITY"],
    relations: ["RELATED_TO"],
    description: "Compile explicit business relations between logical entities.",
    runtime: "design",
  },
  {
    key: "entity-dimension-level-mapping",
    path: "/entity/v1/levelRelationByEntity",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["LOGICAL_ENTITY", "LOGICAL_ATTRIBUTE", "DIMENSION", "DIMENSION_LEVEL"],
    relations: ["USES_DIMENSION", "MAPS_TO_LEVEL"],
    description: "Map logical entities and attributes to dimensions and levels.",
    runtime: "design",
  },
  {
    key: "dimension-level-lineage",
    path: "/entity/v1/levelLineageByEntity",
    alternativePaths: ["/entity/v1/entityLevelLineage"],
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["LOGICAL_ENTITY", "DIMENSION_HIERARCHY", "DIMENSION_LEVEL"],
    relations: ["ROLLS_UP_TO", "RELATED_LEVEL"],
    description: "Compile explicit level-to-level roll-up or related-level edges.",
    runtime: "design",
  },
  {
    key: "dimension-domain",
    path: "/plat/meta/v1/dimensions/",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["DIMENSION"],
    relations: [],
    description: "Authoritative Dimension inventory; replaces legacy level-list discovery.",
    runtime: "runtime",
  },
  {
    key: "dimension-detail",
    path: "/plat/meta/v1/dimensions/{dimensionName}",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "read",
    assetTypes: ["DIMENSION"],
    relations: [],
    description: "Read one Dimension definition.",
    runtime: "runtime",
  },
  {
    key: "dimension-levels",
    path: "/plat/meta/v1/dimensions/{dimensionName}/levels",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["DIMENSION", "DIMENSION_LEVEL"],
    relations: ["HAS_LEVEL"],
    description: "Expand a Dimension to its levels.",
    runtime: "runtime",
  },
  {
    key: "dimension-hierarchies",
    path: "/plat/meta/v1/dimensions/{dimensionName}/hierarchies",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["DIMENSION", "DIMENSION_HIERARCHY", "DIMENSION_LEVEL"],
    relations: ["HAS_HIERARCHY", "HAS_LEVEL"],
    description: "Expand a Dimension to hierarchies and ordered levels.",
    runtime: "runtime",
  },
  {
    key: "dimension-attributes",
    path: "/plat/meta/v1/dimensions/{dimensionName}/levels/{levelName}/attributes",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["DIMENSION_LEVEL", "DIMENSION_ATTRIBUTE"],
    relations: ["HAS_ATTRIBUTE"],
    description: "Expand a Dimension level to attributes.",
    runtime: "runtime",
  },
  {
    key: "measure-list",
    path: "/measure/v1/measureList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["MEASURE", "LOGICAL_ENTITY", "LOGICAL_ATTRIBUTE", "DIMENSION_LEVEL"],
    relations: ["PROVIDES_MEASURE", "AVAILABLE_BY", "CALCULATED_FROM"],
    description: "Compile measures, formulas, aggregation, units and entity/dimension/measure relations.",
    runtime: "design",
  },
  {
    key: "indicator-list",
    path: "/indicator/v1/indicatorList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["INDICATOR", "INDICATOR_VARIABLE", "MEASURE", "DIMENSION_LEVEL"],
    relations: [
      "CALCULATED_FROM",
      "AVAILABLE_BY",
      "USES_VARIABLE",
      "ASSOCIATED_WITH",
      "REFERENCES",
      "DRILL_DOWN",
      "ABNORMAL_DRILL",
    ],
    description: "Compile indicators, formulas, units, aggregation levels and measure/indicator relations.",
    runtime: "design",
  },
  {
    key: "physical-model-list",
    path: "/table/v1/tableList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["PHYSICAL_TABLE"],
    relations: [],
    description: "Discover physical models, preferably incrementally by update timestamp.",
    runtime: "design",
  },
  {
    key: "physical-columns",
    path: "/table/v1/columnListById",
    alternativePaths: ["/table/v1/columnByTableId"],
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["PHYSICAL_TABLE", "PHYSICAL_COLUMN"],
    relations: ["HAS_COLUMN"],
    description: "Expand a physical model to physical columns.",
    runtime: "design",
  },
  {
    key: "logical-physical-models",
    path: "/entity/v1/phyModelList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["LOGICAL_ENTITY", "PHYSICAL_TABLE"],
    relations: ["IMPLEMENTED_BY"],
    description: "Compile authoritative logical-to-physical model mappings.",
    runtime: "runtime",
  },
  {
    key: "physical-lineage-v2",
    path: "/meta/lineage/v2/queryByModel",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["PHYSICAL_TABLE", "PHYSICAL_COLUMN", "DATA_FLOW"],
    relations: ["UPSTREAM_OF", "DERIVES_TO", "TRANSFORMED_BY"],
    description: "Compile table lineage, column lineage and transformation-flow edges.",
    runtime: "runtime",
  },
  {
    key: "catalog-tree",
    path: "/catalog/v1/catalogList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["CATALOG"],
    relations: ["HAS_CHILD", "BELONGS_TO_CATALOG"],
    description: "Compile the Catalog tree without assuming every Catalog node is a warehouse layer.",
    runtime: "design",
  },
  {
    key: "aggregate-model-list",
    path: "/aggregateModel/v1/aggregateModelList",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "search",
    assetTypes: ["AGGREGATE_MODEL", "LOGICAL_ENTITY"],
    relations: ["MAPS_TO"],
    description: "Compile aggregate models and their logical-entity mapping.",
    runtime: "runtime",
  },
  {
    key: "aggregate-model-sources",
    path: "/aggregateModel/v1/srcPhyModelListByAggregateModel",
    priority: "P0",
    phase: "compiler",
    authority: "primary",
    role: "expand",
    assetTypes: ["AGGREGATE_MODEL", "PHYSICAL_TABLE"],
    relations: ["SOURCE_MODEL"],
    description: "Compile aggregate-model source physical models.",
    runtime: "design",
  },
  {
    key: "entity-semantic-bundle",
    path: "/entity/v1/entityColumnRelationById",
    priority: "P1",
    phase: "serving",
    authority: "verification",
    role: "expand",
    assetTypes: [
      "LOGICAL_ENTITY",
      "LOGICAL_ATTRIBUTE",
      "PHYSICAL_TABLE",
      "PHYSICAL_COLUMN",
      "DIMENSION_LEVEL",
      "MEASURE",
      "INDICATOR",
    ],
    relations: ["IMPLEMENTED_BY", "MAPS_TO", "MAPS_TO_LEVEL", "PROVIDES_MEASURE"],
    description: "Serve or cross-check a pre-assembled local semantic bundle; not the Compiler fact authority.",
    runtime: "runtime",
  },
  {
    key: "legacy-dimension-level-list",
    path: "/meta/levels/list",
    priority: "P1",
    phase: "serving",
    authority: "fallback",
    role: "search",
    assetTypes: ["DIMENSION_LEVEL"],
    relations: [],
    description: "Legacy runtime level discovery fallback.",
    runtime: "runtime",
  },
  {
    key: "legacy-model-dimension-relation",
    path: "/plat/meta/v1/table/queryDimTable",
    priority: "P1",
    phase: "serving",
    authority: "verification",
    role: "expand",
    assetTypes: ["LOGICAL_ENTITY", "DIMENSION"],
    relations: ["USES_DIMENSION"],
    description: "Compatibility lookup and consistency check for model-dimension relations.",
    runtime: "runtime",
  },
  {
    key: "legacy-dimension-rollup",
    path: "/metaone/inner/plat/meta/v1/table/rollUpDimQuery",
    priority: "P1",
    phase: "serving",
    authority: "verification",
    role: "expand",
    assetTypes: ["DIMENSION_LEVEL"],
    relations: ["ROLLS_UP_TO"],
    description: "Compatibility lookup and consistency check for dimension roll-ups.",
    runtime: "runtime",
  },
  {
    key: "runtime-measure-list",
    path: "/meta/counters/list",
    priority: "P1",
    phase: "serving",
    authority: "supplemental",
    role: "search",
    assetTypes: ["MEASURE"],
    relations: [],
    description: "Runtime counter supplement; never merge Measure and Indicator types.",
    runtime: "runtime",
  },
  {
    key: "runtime-indicator-list",
    path: "/meta/models/list",
    priority: "P1",
    phase: "serving",
    authority: "supplemental",
    role: "search",
    assetTypes: ["INDICATOR"],
    relations: [],
    description: "Runtime indicator supplement.",
    runtime: "runtime",
  },
  {
    key: "legacy-physical-lineage",
    path: "/DataLineage/backendService/lineage/v1/queryByModel",
    alternativePaths: ["/plat/meta/v1/lineage/getPhyTableLineage", "/table/v1/tableLineage"],
    priority: "P1",
    phase: "serving",
    authority: "fallback",
    role: "expand",
    assetTypes: ["PHYSICAL_TABLE"],
    relations: ["UPSTREAM_OF"],
    description: "Fallback table-level lineage when v2 lineage is unavailable.",
    runtime: "cross-service",
  },
] as const;

export const METAONE_ASSET_TYPES = [
  ...new Set(METAONE_ENDPOINTS.flatMap((endpoint) => endpoint.assetTypes)),
].sort() as AssetType[];

export const METAONE_RELATIONS = [
  ...new Set(METAONE_ENDPOINTS.flatMap((endpoint) => endpoint.relations)),
].sort();

export const METAONE_COMPILER_ENDPOINTS = METAONE_ENDPOINTS.filter(
  (endpoint) => endpoint.phase === "compiler" && endpoint.authority === "primary",
);
